version: '3'

services:
  db:
    image: mongo:3.0
    networks:
      appnetwork:
        aliases:
          - db
  api:
    build:
      context: .
    command: npm run start
    environment:
      MONGODB_URI: db
    ports:
      - "8000:3000"
    depends_on:
      - db
    networks:
      appnetwork:
        aliases:
          - eventsapi

networks:
  appnetwork: