swagger: '2.0'
info:
  version: 0.0.1
  title: Events
  description: |
    #### Events API that contain a simple event type resource.
schemes:
  - http
basePath: /v1
paths:
  /events:
    get:
      responses:
        '200':
          description: Get list of events.
          schema:
            type: array
            items:
              $ref: '#/definitions/Event'
    post:
      responses:
        '200':
          description: Create new event.
          schema:
            $ref: '#/definitions/Event'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      parameters:
        - name: name
          in: formData
          description: name
          type: string
        - name: year
          in: formData
          description: year
          type: string
  '/events/{id}':
    parameters:
      - name: id
        in: path
        description: ID
        type: string
        required: true
    get:
      responses:
        '200':
          description: Get single event by ID.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Event:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier representing a specific event.
      description:
        type: string
        description: Description of product.
      type:
        type: string
        description: Type of event.
      created_date:
        type: string
        description: Date event was created.
      last_updated:
        type: string
        description: Date event was last updated.
  Error:
    type: object
    properties:
      message:
        type: string
